######!!orchestration_orchestration
# Do not edit this file below this point. Any changes will be overwritten.
#!!orchestration_orchestration
.PHONY:

docker:
	mkdir -p docker/.build
	git archive --format tar.gz -o docker/.build/context.tar.gz master
	docker build -t orchestrationdev/testing ./docker/
