production:
  clients:
    default:
      hosts:
        - mongo-prod.example.com
      database: production_db

test:
  clients:
    default:
      hosts:
        - localhost
      database: test_db
