FROM ruby:<%= ruby_version %>
ARG BUNDLE_BITBUCKET__ORG
ARG BUNDLE_GITHUB__COM
RUN apt-get update \
 && apt-get install -y node.js gosu sendmail \
 && rm -rf /var/lib/apt/lists/* \
 && gem install bundler \
 && mkdir /app<%if defined?(Webpacker) %> \
 && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash \
 && . /root/.bashrc \
 && nvm install 10.11.0 \
 && npm install -g yarn<% end %>
WORKDIR /app
COPY .build/Gemfile .build/Gemfile.lock ./
RUN bundle install --without development test --deployment
<% if defined?(Webpacker) %>
COPY .build/package.json .build/yarn.lock ./
RUN . /root/.bashrc && yarn install
<% end %>
ADD .build/context.tar .
<% if defined?(Webpacker) %>RUN . /root/.bashrc && NODE_ENV=production RAILS_ENV=production yarn install && NODE_ENV=production RAILS_ENV=production SECRET_KEY_BASE=abc123 bundle exec rake assets:precompile<% elsif Rake::Task.tasks.map(&:name).include?('assets:precompile') %>RUN NODE_ENV=production RAILS_ENV=production SECRET_KEY_BASE=abc123 bundle exec rake assets:precompile<% end %>
ENTRYPOINT ["/app/orchestration/entrypoint.sh"]
<% case web_server %>
<% when 'puma' %>
CMD ["bundle", "exec", "puma", "-C", "/app/config/puma.rb"]
<% when 'unicorn' %>
CMD ["bundle", "exec", "unicorn", "-c", "/app/config/unicorn.rb"]
<% end %>
